import type { SummaryFraming } from "./types";

// Purchase-side, payment, cross-year and annual (GSTR-9 / 9C) reconciliations that get the same
// guided treatment as the sales-side flows: a problem card (problem / intent / checks), two
// required documents first, every other document offered together as optional, the right summary
// story, and typed phrases that land on them. Everything here is plain data — the script, intent
// card, summary framing and routing are all generated from it (see reconciliation.ts, intents.ts,
// mockResult.ts and resolver.ts).
//
// `id` is the catalogue id. `base` (default: the catalogue's first two documents) are the required
// documents, in the order they're asked; every other catalogue document becomes an optional round,
// then `extra` documents the catalogue doesn't list for that check. `triggers` is a list of token
// sets: the flow matches when ANY set has ALL its tokens in the user's message (see resolver.ts).
// Order matters — the first matching flow wins, so more specific flows come before general ones.

export interface FlowConfig {
  id: string;
  framing?: SummaryFraming;
  base?: string[];
  extra?: string[];
  names?: Record<string, string>;
  /** Replaces a document's catalogue description with one that fits this flow. */
  whys?: Record<string, string>;
  problem: string;
  intent: string;
  checks: [string, string, string];
  triggers?: string[][];
}

export const FLOWS: FlowConfig[] = [
  // ------------------------------------------------------------------ annual (GSTR-9 / 9C)
  {
    id: "8.15",
    framing: "exposure",
    problem: "Your turnover, tax and ITC reconciliations for the year may not add up to a clean GSTR-9C, and some differences are still unexplained.",
    intent: "Bring turnover, taxable turnover, tax paid and ITC together into one annual statement, with a reason for every difference.",
    checks: ["Turnover, taxable turnover, tax and ITC reconciled in one view", "Differences with a reason and an owner", "Anything left unreconciled before GSTR-9C is filed"],
    triggers: [["gstr-9c", "consolidated"], ["gstr-9c", "final"], ["gstr9c", "final"]],
  },
  {
    id: "8.1",
    framing: "mismatch",
    problem: "The turnover and GST figures in your audited financial statements may not agree with your annual return (GSTR-9).",
    intent: "Reconcile the accounts to the return, allocating company-level figures to each GSTIN, and explain the gaps.",
    checks: ["Financial-statement turnover vs GSTR-9 turnover", "Company-level figures allocated to the GSTIN being reconciled", "GST-related income and expense heads vs the return"],
    triggers: [["financial", "statements", "gstr-9"], ["audited", "gstr-9"], ["financial", "statements", "annual"]],
  },
  {
    id: "8.6",
    framing: "mismatch",
    problem: "Your annual taxable turnover may not match once exempt, nil-rated, non-GST and zero-rated supplies are taken out of total turnover.",
    intent: "Derive taxable turnover for the year and confirm it agrees with the taxable value in GSTR-9.",
    checks: ["Total turnover less exempt, nil-rated and non-GST supplies", "Zero-rated and recipient-RCM supplies treated correctly", "Derived taxable turnover vs GSTR-9 Tables 7 and 8"],
    triggers: [["taxable", "turnover"]],
  },
  {
    id: "8.7",
    framing: "exposure",
    base: ["F17", "F14"],
    problem: "The tax payable you reported by rate in GSTR-9 may not match the tax recalculated from your sales for the year.",
    intent: "Recompute the year's GST liability by rate and tax head, and find any difference from what GSTR-9 shows as payable.",
    checks: ["Sales recalculated by rate and tax head", "Recomputed tax vs tax payable in GSTR-9 Tables 9 and 10", "Differences by rate slab"],
    triggers: [["rate-wise", "tax"], ["ratewise", "tax"], ["rate", "wise", "tax"]],
  },
  {
    id: "8.8",
    framing: "exposure",
    problem: "Reconciling the year may have uncovered additional tax payable, and it's not yet clear whether it has been paid.",
    intent: "Work out the extra tax due from the unresolved differences and track whether it has been paid before GSTR-9 is filed.",
    checks: ["Additional tax from unresolved turnover and tax differences", "Payment through the ledgers or DRC-03", "Balance still payable (GSTR-9 Table 11)"],
    triggers: [["additional", "tax", "payable"], ["additional", "liability", "gstr-9"], ["additional", "liability", "annual"]],
  },
  {
    id: "8.9",
    framing: "mismatch",
    base: ["F14", "F07"],
    problem: "The ITC in your books for the year may not agree with the ITC claimed in your annual return.",
    intent: "Reconcile books ITC to GSTR-9, allowing for timing differences, reversals and prior or next-year items.",
    checks: ["Books ITC by tax head vs ITC in GSTR-9 Tables 12 and 13", "Reversals and reclaims for the year", "Timing differences across financial years"],
    triggers: [["books", "itc", "gstr-9"], ["itc", "gstr-9"], ["itc", "annual", "books"]],
  },
  {
    id: "8.10",
    framing: "mismatch",
    problem: "ITC by expense and capital-goods head in your books may not agree with what was claimed.",
    intent: "Reconcile ITC against the annual expense and asset heads in your books, so each head ties to the return.",
    checks: ["ITC by expense and capital-goods head", "Heads vs the trial balance and the input GST ledger", "Differences by head (GSTR-9 Table 14)"],
    triggers: [["expense", "head", "itc"], ["expense", "heads", "itc"]],
  },
  {
    id: "8.11",
    framing: "mismatch",
    problem: "The ITC in your annual return may not be supported by the year's GSTR-2B and your purchase and expense records.",
    intent: "Use the year's GSTR-2B and purchase data as evidence for the ITC in your books and annual return.",
    checks: ["Annual GSTR-2B vs purchase and expense ITC", "Both vs ITC in GSTR-9", "ITC claimed without 2B support"],
    triggers: [["gstr-2b", "gstr-9"], ["gstr-2b", "annual"]],
  },
  {
    id: "8.12",
    framing: "mismatch",
    problem: "Some ITC is booked in one financial year but claimed in another, which makes the annual ITC figures disagree.",
    intent: "Separate ITC booked in one year but availed in another, so the annual books-to-return ITC reconciliation is correct.",
    checks: ["ITC booked this year but claimed next year", "ITC booked last year but claimed this year", "Timing items excluded from the annual comparison"],
    triggers: [["prior", "next", "year", "itc"], ["itc", "timing", "year"], ["itc", "claimed", "late"], ["itc", "late", "year"]],
  },
  {
    id: "8.13",
    framing: "exposure",
    problem: "Reverse-charge tax and the ITC on it may not agree between your books, GSTR-3B and GSTR-9 for the year.",
    intent: "Reconcile the year's RCM taxable value, tax paid and ITC taken, so nothing is under-paid or over-claimed.",
    checks: ["RCM liability in books vs GSTR-3B", "RCM tax paid vs RCM ITC claimed", "Both vs GSTR-9"],
    triggers: [["rcm", "annual"], ["rcm", "year-end"], ["rcm", "yearly"], ["reverse", "charge", "annual"], ["reverse", "charge", "year-end"], ["rcm", "gstr-9"]],
  },
  {
    id: "8.14",
    framing: "exposure",
    problem: "Additional tax or interest paid through DRC-03 outside normal returns may not be matched to the differences it was meant to cover.",
    intent: "Match each DRC-03 payment to the annual difference it settles, and see what is still unpaid.",
    checks: ["DRC-03 payments for the year", "Payments matched to liabilities and interest", "Differences left unpaid"],
    triggers: [["drc-03", "annual"], ["drc-03", "gstr-9"], ["additional", "payment", "drc-03"]],
  },
  {
    id: "8.4",
    framing: "mismatch",
    problem: "Your twelve monthly GSTR-3B returns may not add up to your annual return (GSTR-9).",
    intent: "Confirm the periodic returns roll up correctly into GSTR-9, and find the month or head where they don't.",
    checks: ["Twelve months of GSTR-3B vs GSTR-9 totals", "Differences by tax head", "Amendments and prior-year items in the gap"],
    triggers: [["gstr-3b", "gstr-9"]],
  },
  {
    id: "8.2",
    framing: "mismatch",
    names: { F18: "GSTR-1 / GSTR-1A" },
    problem: "Revenue in your books for the year may not agree with the outward supplies reported through GSTR-1 and GSTR-1A.",
    intent: "Reconcile full-year book revenue to GSTR-1 and GSTR-1A, with the reasons for any gap.",
    checks: ["Books turnover vs GSTR-1 and GSTR-1A for the year", "Credit and debit notes in between", "Unexplained differences"],
  },
  {
    id: "8.3",
    framing: "exposure",
    names: { F18: "GSTR-1 / GSTR-1A" },
    problem: "The tax reported in your GSTR-1 for the year may differ from the liability declared in your GSTR-3B returns.",
    intent: "Compare annual outward-supply reporting with the tax declared month by month, and find short payments.",
    checks: ["GSTR-1 and GSTR-1A tax by month", "Liability declared in GSTR-3B", "Months with a gap"],
  },
  {
    id: "8.16",
    framing: "exposure",
    problem:
      "Transactions of this year that you reported in the next year (amendments, credit notes, missed invoices, ITC claimed late) may not be separated out, so this year's annual figures could be wrong.",
    intent: "Identify what belongs to this year but was reported in the next, up to the 30 November cut-off, so it goes in the right GSTR-9 tables.",
    checks: ["Amendments, credit notes and missed invoices reported next year", "ITC for this year claimed in the next return", "Whether each falls inside the cut-off for the next-year tables"],
    triggers: [["november", "amendments"], ["november", "credit", "notes"], ["next", "financial", "year", "reported"], ["reported", "next", "year"]],
  },
  {
    id: "8.17",
    framing: "exposure",
    names: { F18: "GSTR-1" },
    whys: { F18: "Shows the credit notes you reported, so each can be checked against the time limit." },
    problem: "Credit notes you issued under Section 34 may be outside the time limit, or the recipient may not have reversed the ITC on them.",
    intent: "Check each credit note against the time limit and confirm the ITC reversal on the other side.",
    checks: ["Credit note dates vs the Section 34 time limit", "Credit notes reported in GSTR-1", "ITC reversed by the recipient"],
    triggers: [["section", "credit", "note"], ["section", "credit", "notes"], ["credit", "notes", "time", "limit"], ["credit", "note", "timing"]],
  },
  {
    id: "8.18",
    framing: "mismatch",
    problem: "Items from the previous year that were reported this year may still be in this year's annual figures.",
    intent: "Find prior-year items reported this year and exclude them, so this year's GSTR-9 figures are clean.",
    checks: ["Prior-year invoices, notes and ITC reported this year", "Items already in this year's totals", "Adjusted figures for GSTR-9"],
    triggers: [["prior", "year", "items"], ["prior-year"], ["prior", "year", "adjustments"], ["previous", "year", "items"]],
  },

  // ------------------------------------------------------------------ purchase side & ITC
  {
    id: "3.6",
    framing: "exposure",
    problem: "ITC claimed in GSTR-3B may be more than what is eligible or supported, which would need to be reversed with interest.",
    intent: "Find ITC claimed above what GSTR-2B and your own working support, before it becomes a notice.",
    checks: ["ITC claim working vs GSTR-2B", "Claim working vs GSTR-3B", "Excess claimed, by tax head"],
    triggers: [["excess", "itc"], ["itc", "exceeds"], ["itc", "exceeds", "gstr-2b"], ["claimed", "more", "itc"]],
  },
  {
    id: "3.3",
    framing: "recovery",
    extra: ["F10", "F29"],
    problem: "The ITC you claimed in GSTR-3B may not match what GSTR-2B shows as available.",
    intent: "Check that ITC claimed doesn't exceed what 2B supports, and find eligible ITC left unclaimed.",
    checks: ["GSTR-2B available ITC vs ITC claimed in GSTR-3B", "ITC claimed without support in 2B", "Eligible ITC not yet claimed"],
    triggers: [["gstr-2b", "gstr-3b"], ["itc", "claimed", "gstr-2b"]],
  },
  {
    id: "3.4",
    framing: "recovery",
    problem: "GSTR-2B, your ITC claim working and GSTR-3B may not agree with each other.",
    intent: "Trace ITC end to end, from what the portal shows to what you decided to claim to what you filed.",
    checks: ["GSTR-2B vs claim working", "Claim working vs GSTR-3B", "Gaps at each step"],
    triggers: [["claim", "working", "gstr-2b"]],
  },
  {
    id: "3.2",
    framing: "mismatch",
    problem: "Your invoice-level ITC claim working may not tie to the ITC totals in the filed GSTR-3B.",
    intent: "Make sure the ITC you worked out invoice by invoice is what was filed.",
    checks: ["Claim working totals by tax head", "ITC in GSTR-3B", "Differences by head"],
    triggers: [["claim", "working", "gstr-3b"]],
  },
  {
    id: "3.7",
    framing: "recovery",
    problem: "Eligible ITC may have been deferred or never claimed.",
    intent: "Find ITC you're entitled to but haven't claimed, before the time limit.",
    checks: ["GSTR-2B ITC not in your claim", "Invoices deferred on purpose", "Claim deadlines"],
    triggers: [["unclaimed", "itc"], ["deferred", "itc"]],
  },
  {
    id: "1.9",
    framing: "mismatch",
    problem: "Supplier GSTINs on your purchase invoices may not match the GSTINs on the portal.",
    intent: "Find GSTIN differences that stop invoices from matching and ITC from flowing.",
    checks: ["Supplier GSTIN in books vs GSTR-2A and 2B", "Same supplier under more than one GSTIN", "Invoices blocked by a GSTIN difference"],
    triggers: [["supplier", "gstin"], ["vendor", "gstin"], ["gstin", "mismatch", "vendor"]],
  },
  {
    id: "1.12",
    framing: "mismatch",
    problem: "Taxable values on your purchase invoices may differ from what suppliers reported.",
    intent: "Find value differences between your books and the portal, so ITC is claimed on the right amount.",
    checks: ["Taxable value per invoice in books vs GSTR-2A and 2B", "Differences above a tolerance", "Invoices where only part of the ITC is supported"],
    triggers: [["taxable", "value", "purchase"], ["taxable", "value", "gstr-2b"], ["taxable", "value", "vendor"]],
  },
  {
    id: "1.4",
    framing: "recovery",
    problem: "Your purchase register, GSTR-2A and GSTR-2B may each show a different set of invoices.",
    intent: "Give every invoice one status across books, supplier reporting and the period-wise ITC statement.",
    checks: ["Each invoice in books, 2A and 2B", "Invoices in one source but not the others", "Value and period differences"],
    triggers: [["gstr-2a", "gstr-2b", "books"], ["gstr-2a", "gstr-2b", "bill"], ["gstr-2a", "gstr-2b", "purchase"]],
  },
  {
    id: "1.1",
    framing: "recovery",
    problem: "Purchase invoices in your books may not be in your suppliers' reporting (GSTR-2A).",
    intent: "Find invoices suppliers haven't reported, and amendments that change them.",
    checks: ["Purchase invoices in books vs GSTR-2A", "Suppliers who haven't filed", "Amendments after the original invoice"],
    triggers: [["gstr-2a", "bill"], ["gstr-2a", "purchase"], ["gstr-2a", "books"]],
  },
  {
    id: "1.2",
    framing: "recovery",
    extra: ["F01"],
    problem: "Purchase invoices in your books may be missing from GSTR-2B, so the ITC on them isn't available to claim.",
    intent: "Find invoices missing in 2B, vendors who haven't filed, value or GSTIN mismatches and wrong-period reporting.",
    checks: ["Invoice-level match of books to GSTR-2B", "Vendors who haven't filed or filed late", "Value, GSTIN and period differences"],
    triggers: [["gstr-2b", "bill"], ["gstr-2b", "purchase"], ["gstr-2b", "vendor"], ["gstr-2b", "missing"], ["gstr-2b", "books"]],
  },
  {
    id: "9.7",
    framing: "recovery",
    problem: "The invoice actions you took in IMS, GSTR-2B and your ITC claim may not agree.",
    intent: "Reconcile accepted, rejected and pending IMS actions with what 2B shows and what you claimed.",
    checks: ["IMS actions vs GSTR-2B", "Accepted invoices vs ITC claimed", "Pending and rejected invoices still in your claim"],
    triggers: [["ims", "claim"], ["ims", "itc"]],
  },
  {
    id: "9.2",
    framing: "mismatch",
    problem: "Actions taken in the Invoice Management System (IMS) may not be reflected in your GSTR-2B.",
    intent: "Check that every accept, reject or pending action flows through to 2B correctly.",
    checks: ["IMS action per invoice", "The 2B that resulted", "Differences between the two"],
    triggers: [["ims", "gstr-2b"], ["ims"], ["invoice", "management", "system"]],
  },
  {
    id: "2.5",
    framing: "mismatch",
    problem: "The input GST in your books may not agree with the credit shown in GSTR-2B.",
    intent: "Compare the input CGST, SGST and IGST balances in your ledger with what the portal shows.",
    checks: ["Input GST ledger by tax head", "GSTR-2B ITC by tax head", "Invoices posted in one but not the other"],
    triggers: [["input", "ledger", "gstr-2b"]],
  },
  {
    id: "2.2",
    framing: "mismatch",
    problem: "CGST, SGST and IGST may be posted to the wrong input accounts in your books.",
    intent: "Make sure each invoice's tax is posted to the right tax-head ledger.",
    checks: ["Tax head on each invoice vs the ledger posting", "Postings to the wrong account", "Balances by head vs credits taken"],
    triggers: [["input", "tax", "head"], ["input", "cgst", "ledger"], ["input", "igst", "ledger"]],
  },
  {
    id: "5.3",
    framing: "mismatch",
    problem: "The GST receivable in your books may not agree with the credit shown in the Electronic Credit Ledger.",
    intent: "Bridge the books-side input GST to the portal ledger, and explain every difference.",
    checks: ["Input GST in books vs credit ledger balance", "Timing and unclaimed items in between", "Remaining unexplained difference"],
    triggers: [["receivable", "credit", "ledger"], ["books", "credit", "ledger"], ["gl", "credit", "ledger"]],
  },
  {
    id: "5.1",
    framing: "mismatch",
    problem: "The ITC in your filed GSTR-3B may not be reflected in your Electronic Credit Ledger.",
    intent: "Confirm each filed ITC and reversal movement shows up in the portal credit ledger.",
    checks: ["ITC and reversals in GSTR-3B", "Movements in the credit ledger", "Differences by period"],
    triggers: [["gstr-3b", "electronic", "credit", "ledger"], ["gstr-3b", "credit", "ledger"]],
  },
  {
    id: "17.1",
    framing: "exposure",
    problem: "ITC that is blocked or ineligible (for example under Section 17(5)) may have been claimed.",
    intent: "Find blocked credits claimed in returns, so they can be reversed before a notice.",
    checks: ["Invoices in blocked categories", "ITC claimed on them in GSTR-3B", "Amount to reverse"],
    triggers: [["blocked"], ["ineligible", "itc"]],
  },
  {
    id: "17.4",
    framing: "exposure",
    problem: "Common credit used for both taxable and exempt supplies may not have been apportioned and reversed correctly under Rules 42 and 43.",
    intent: "Check the common-credit reversal against the required working, and find the true-up needed.",
    checks: ["Common credit and its apportionment", "Reversal in books and GSTR-3B", "Difference from the required reversal"],
    triggers: [["common", "credit"], ["common", "itc"]],
  },
  {
    id: "17.2",
    framing: "exposure",
    problem: "ITC may have been claimed on invoices past the time limit.",
    intent: "Find invoices outside the ITC time limit and separate the credit that can no longer be claimed.",
    checks: ["Invoice dates vs the time limit", "ITC claimed after the limit", "Credit to reverse"],
    triggers: [["time-barred"], ["time", "barred"], ["180", "days"]],
  },
  {
    id: "17.5",
    framing: "recovery",
    problem: "ITC you reversed temporarily may never have been reclaimed.",
    intent: "Find reversals that are now eligible to be reclaimed, and claim the credit back.",
    checks: ["Temporary reversals and their reason", "Whether the condition is now met", "ITC eligible to reclaim"],
    triggers: [["reversal", "reclaim"], ["temporary", "reversal"], ["reclaim"]],
  },
  {
    id: "17.6",
    framing: "exposure",
    problem: "Credit notes received from suppliers may not have been reflected in your ITC reversal.",
    intent: "Make sure ITC is reversed for every supplier credit note or downward amendment.",
    checks: ["Supplier credit notes and amendments", "ITC reversed in your claim", "Credit notes not yet reflected"],
    triggers: [["supplier", "credit", "note", "reversal"], ["credit", "note", "itc", "reversal"], ["vendor", "credit", "note"]],
  },
  {
    id: "4.5",
    framing: "mismatch",
    problem: "ITC reversals and reclaims in your working may not match the portal's Electronic Credit Reversal and Reclaimed statement.",
    intent: "Tie your reversal and reclaim register to the portal statement and to GSTR-3B.",
    checks: ["Reversals and reclaims in your register", "The portal statement", "Differences by period"],
    triggers: [["reversal", "credit", "ledger"], ["credit", "reversal", "reclaimed", "statement"], ["reclaimed", "statement"]],
  },
  {
    id: "17.8",
    framing: "mismatch",
    problem: "ITC on capital goods may not match the additions recorded in your fixed asset register.",
    intent: "Make sure ITC claimed on capital goods agrees with the assets you actually capitalised.",
    checks: ["Capital goods ITC claimed", "Additions in the fixed asset register", "Assets with ITC but no addition, or the reverse"],
    triggers: [["capital", "goods"], ["fixed", "asset"], ["fixed", "assets"], ["capex"]],
  },
  {
    id: "17.9",
    framing: "exposure",
    problem: "Suppliers you haven't paid within 180 days may still have ITC claimed on them, which has to be reversed under Rule 37.",
    intent: "Find ITC on invoices unpaid beyond 180 days, and the reversal and later reclaim on payment.",
    checks: ["Invoices unpaid beyond 180 days", "ITC claimed on them", "Reversal made, and reclaim after payment"],
    triggers: [["rule", "unpaid", "supplier"], ["unpaid", "vendors", "itc"], ["unpaid", "supplier", "itc"], ["180", "days", "unpaid"]],
  },

  // ------------------------------------------------------------------ reverse charge
  {
    id: "7.3",
    framing: "exposure",
    problem: "ITC taken on reverse-charge tax may not match the tax actually paid or be claimed in the right period.",
    intent: "Confirm RCM ITC is claimed only after the tax is paid, and in the right month.",
    checks: ["RCM tax paid in cash", "RCM ITC claimed in GSTR-3B", "Claims ahead of payment"],
    triggers: [["rcm", "itc"]],
  },
  {
    id: "7.2",
    framing: "exposure",
    problem: "Reverse-charge liability in your books may not be paid in GSTR-3B.",
    intent: "Find RCM tax that is due but not reported or paid in the return.",
    checks: ["RCM liability in your working", "RCM tax in GSTR-3B", "Short or missing payment"],
    triggers: [["rcm", "liability", "gstr-3b"], ["rcm", "gstr-3b"], ["rcm", "cash"]],
  },
  {
    id: "7.1",
    framing: "exposure",
    problem: "Expenses that attract reverse charge (legal fees, GTA, import of services, security services, director payments) may not all be in your RCM working.",
    intent: "Find RCM expenses in the books that never reached your RCM liability.",
    checks: ["Expense ledgers that attract RCM", "RCM liability working", "Expenses missing from the working"],
    triggers: [["rcm", "bills"], ["rcm", "expense"], ["rcm", "expenses"], ["legal", "fees", "rcm"], ["gta"], ["goods", "transport", "agency"]],
  },
  {
    id: "7.4",
    framing: "exposure",
    base: ["F05", "F13"],
    problem: "Reverse-charge bills, your ledgers, your RCM working and your ITC claim may not agree.",
    intent: "Trace RCM from the bill to the liability paid to the ITC claimed, and find where it breaks.",
    checks: ["RCM bills vs ledger postings", "Liability paid vs ITC claimed", "Gaps at each step"],
    triggers: [["rcm"], ["reverse", "charge"]],
  },

  // ------------------------------------------------------------------ imports & ISD
  {
    id: "12.1",
    framing: "mismatch",
    problem: "Imports in your Bill of Entry data may not appear in GSTR-2B, so the IGST credit may not be available.",
    intent: "Match each bill of entry to the import data in GSTR-2B.",
    checks: ["Bills of entry vs GSTR-2B import data", "IGST by bill", "Bills missing in 2B"],
    triggers: [["bill", "entry", "gstr-2b"], ["boe", "gstr-2b"]],
  },
  {
    id: "12.4",
    framing: "mismatch",
    problem: "Import data from ICEGATE may not agree with what GSTR-2B shows.",
    intent: "Confirm the IGST on imports reported by customs reaches your 2B.",
    checks: ["ICEGATE import data", "GSTR-2B import section", "Differences by bill"],
    triggers: [["icegate"], ["icegate", "gstr-2b"]],
  },
  {
    id: "12.7",
    framing: "mismatch",
    problem: "ITC on imports may not be claimed in the right period or tax head in GSTR-3B.",
    intent: "Confirm import IGST is claimed once, in the right month and head.",
    checks: ["Import ITC in your working", "Import ITC in GSTR-3B", "Period and head differences"],
    triggers: [["import", "itc", "gstr-3b"]],
  },
  {
    id: "12.8",
    framing: "mismatch",
    problem: "Bills of entry, ICEGATE data, GSTR-2B, your books and your ITC claim for imports may not agree.",
    intent: "Trace imported goods from the purchase to customs to the credit claimed, and find where they differ.",
    checks: ["Bill of entry vs ICEGATE vs GSTR-2B", "Import IGST in books and the claim", "Imports not claimed or claimed twice"],
    triggers: [["import", "itc"], ["imports", "goods"], ["bill", "entry"], ["boe"]],
  },
  {
    id: "13.2",
    framing: "mismatch",
    problem: "ITC distributed by the ISD may not appear in the recipient branch's GSTR-2B.",
    intent: "Confirm each distribution in GSTR-6 reaches the right branch's 2B.",
    checks: ["GSTR-6 distribution by branch GSTIN", "Credit in each recipient's 2B", "Branches with a difference"],
    triggers: [["isd", "gstr-2b"], ["isd", "recipient"]],
  },
  {
    id: "13.5",
    framing: "mismatch",
    problem: "Credit distributed to a branch may not be the credit it claimed in GSTR-3B.",
    intent: "Make sure each branch claims the ITC it was distributed, no more and no less.",
    checks: ["ITC distributed to the branch", "ITC claimed in GSTR-3B", "Difference by branch"],
    triggers: [["isd", "gstr-3b"], ["distributed", "itc", "gstr-3b"]],
  },
  {
    id: "13.1",
    framing: "mismatch",
    problem: "Purchase ITC in your ISD records may not agree with the credit distributed in GSTR-6.",
    intent: "Reconcile the ITC received by the ISD with what it distributed.",
    checks: ["ISD purchase ITC", "Distribution in GSTR-6", "Undistributed or excess credit"],
    triggers: [["isd", "gstr-6"], ["gstr-6"]],
  },
  {
    id: "13.6",
    framing: "mismatch",
    problem: "Input service distribution may not tie from the ISD's purchases to each branch's claim.",
    intent: "Trace credit from the ISD source through distribution to each branch's books and return.",
    checks: ["ISD source vs distribution", "Distribution vs recipient 2B and books", "Branch claims in GSTR-3B"],
    triggers: [["isd"], ["input", "service", "distributor"]],
  },

  // ------------------------------------------------------------------ payments & ledgers
  {
    id: "18.3",
    framing: "exposure",
    problem: "A DRC-01B difference may not be explained or paid.",
    intent: "Match the difference raised to your explanation or DRC-03 payment.",
    checks: ["Difference raised in DRC-01B", "Your response and any payment", "Amount still open"],
    triggers: [["drc-01b", "explanation"], ["drc-01b", "drc-03"]],
  },
  {
    id: "18.1",
    framing: "exposure",
    names: { F18: "GSTR-1" },
    whys: { F18: "Shows the outward tax you declared in GSTR-1, to compare with what you paid in GSTR-3B." },
    problem: "Tax declared in GSTR-1 may be more than the tax paid in GSTR-3B, which can trigger a DRC-01B intimation.",
    intent: "Spot the liability gap early and fix it before the intimation arrives.",
    checks: ["GSTR-1 liability vs GSTR-3B", "Difference by month", "Differences large enough to trigger DRC-01B"],
    triggers: [["drc-01b"]],
  },
  {
    id: "11.4",
    framing: "mismatch",
    problem: "The liability on the portal may not be fully matched by the cash and credit you used to pay it.",
    intent: "Confirm each liability was paid from the right ledger, with nothing left over.",
    checks: ["Liability ledger", "Cash and credit utilisation", "Unmatched liability"],
    triggers: [["utilisation"], ["utilization"]],
  },
  {
    id: "11.3",
    framing: "mismatch",
    problem: "The cash you paid may not match the cash portion of your GSTR-3B liability.",
    intent: "Reconcile the electronic cash ledger and challans to what GSTR-3B says was paid in cash.",
    checks: ["Cash ledger movements", "Challans paid", "Cash payable in GSTR-3B"],
    triggers: [["cash", "ledger"]],
  },
  {
    id: "11.1",
    framing: "mismatch",
    problem: "The liability in your GSTR-3B may not be the liability shown in the Electronic Liability Ledger.",
    intent: "Confirm every liability you declared appears in the portal ledger.",
    checks: ["GSTR-3B liability", "Liability ledger entries", "Differences by period"],
    triggers: [["gstr-3b", "liability", "ledger"], ["liability", "ledger"]],
  },
  {
    id: "11.5",
    framing: "exposure",
    problem: "Tax paid voluntarily through DRC-03 may not match the additional liability it was meant to cover.",
    intent: "Match each DRC-03 payment to the liability it settles and see what remains.",
    checks: ["DRC-03 payments", "Liability they relate to", "Unmatched payment or liability"],
    triggers: [["drc-03"], ["drc03"], ["voluntary", "payment"]],
  },
  {
    id: "11.6",
    framing: "exposure",
    problem: "Interest, late fees or penalties you paid may not match what was actually due.",
    intent: "Recompute what was due, and find short or excess payment.",
    checks: ["Interest and late fee due by return", "Amounts paid", "Short or excess payment"],
    triggers: [["interest", "late"], ["late", "fee"], ["late", "fees"], ["interest", "penalty"], ["penalties"]],
  },
  {
    id: "11.8",
    framing: "exposure",
    problem: "Tax payable and tax paid may not agree across your returns and the portal ledgers.",
    intent: "Bring liability, payment and credit together in one view and find any tax still unpaid.",
    checks: ["GSTR-3B liability", "Ledger payments and credit used", "Tax payable but not paid"],
    triggers: [["tax", "payable", "paid"], ["payable", "paid"]],
  },
  {
    id: "18.6",
    framing: "exposure",
    problem: "Demands and orders raised against you may not be matched to what you have paid.",
    intent: "Track each demand or order raised against the payments made, and see what is still open.",
    checks: ["Demands and orders raised", "Payments in the ledgers", "Amount still payable and due dates"],
    triggers: [["demand", "order"], ["demands", "orders"], ["demand", "notice"], ["drc-07"], ["show", "cause"]],
  },

  // ------------------------------------------------------------------ refunds
  {
    id: "15.9",
    framing: "recovery",
    problem: "Refund claims you've filed may be pending longer than expected.",
    intent: "Age every claim and find the cash still to come.",
    checks: ["Claims filed", "Orders issued", "Refunds received and still pending"],
    triggers: [["pending", "refund"], ["refund", "ageing"], ["refund", "aging"]],
  },
  {
    id: "15.7",
    framing: "recovery",
    problem: "Refunds that were sanctioned may not have reached your bank.",
    intent: "Confirm each sanctioned refund was received.",
    checks: ["Refund orders", "Bank receipts", "Sanctioned but not received"],
    triggers: [["refund", "bank"], ["refund", "received"]],
  },
  {
    id: "15.5",
    framing: "recovery",
    problem: "The refund sanctioned may be less than what you claimed.",
    intent: "Compare each claim with the order, and see what was short-sanctioned or rejected.",
    checks: ["Amount claimed (RFD-01)", "Amount sanctioned (RFD-06)", "Short sanction and rejection"],
    triggers: [["rfd-01", "rfd-06"], ["sanction"]],
  },
  {
    id: "15.4",
    framing: "recovery",
    problem: "The refund you applied for may differ from what you were eligible to claim.",
    intent: "Compare the claim with your calculation of eligible refund.",
    checks: ["Refund applied for", "Eligible refund working", "Difference"],
    triggers: [["rfd-01", "eligible"], ["rfd-01", "claim"]],
  },
  {
    id: "15.1",
    framing: "recovery",
    problem: "Zero-rated supplies and related ITC may qualify for a refund that hasn't been identified or claimed.",
    intent: "Find the refund you are eligible to claim for exports and SEZ supplies.",
    checks: ["Zero-rated supplies in the period", "ITC and tax attributable to them", "Eligible refund not yet claimed"],
    triggers: [["refund", "eligibility"], ["refund", "eligible"]],
  },
];

export const FLOW_BY_ID: Record<string, FlowConfig> = Object.fromEntries(FLOWS.map((f) => [f.id, f]));
