// The 204 FSCP close-blocker metrics: 8 domains, 56 close processes.
// Content is verbatim from the static kpi-catalogue.html source. This array
// is generated, not hand-written, and is also the data the downloadable
// /close-kpi-catalogue.pdf is built from — keep the two in sync.

export type Domain = {
  code: string;
  name: string;
  protects: string;
  processCount: number;
  metricCount: number;
};

export type Metric = {
  domain: string;
  code: string;
  process: string;
  metric: string;
  against: string;
};

export const TOTALS = { domains: 8, processes: 56, metrics: 204 } as const;

export const DOMAINS: Domain[] = [
  { code: "IC", name: "Intercompany Finance", protects: "Eliminate intercompany billing, booking, settlement and confirmation blockers.", processCount: 7, metricCount: 28 },
  { code: "CF", name: "Core Finance", protects: "Protect the core books: GL, AP, AR, fixed assets, bank and cash.", processCount: 5, metricCount: 28 },
  { code: "GA", name: "GA Close", protects: "Drive period-end close activities from master data through to P&L review.", processCount: 13, metricCount: 39 },
  { code: "TF", name: "Transaction Finance", protects: "Control transactional close flows across P2P, O2C, inventory and payroll.", processCount: 4, metricCount: 20 },
  { code: "RC", name: "Reporting & Compliance", protects: "Finalise post-close reports, schedules, controls and the consolidation package.", processCount: 8, metricCount: 33 },
  { code: "FP", name: "Financial Planning", protects: "Close budget, forecast and review cycles with approved management inputs.", processCount: 8, metricCount: 24 },
  { code: "PC", name: "Planning & Control", protects: "Validate cost, profit-centre and FP&A control views before management close.", processCount: 3, metricCount: 15 },
  { code: "IR", name: "Intelligence & Risk", protects: "Surface anomalies, recovery opportunities and audit-trail risks early.", processCount: 8, metricCount: 17 },
];

export const METRICS: Metric[] = [
  { domain: "IC", code: "IC", process: "IC billing", metric: "Intercompany invoices not raised", against: "Against all intercompany invoices due in the period" },
  { domain: "IC", code: "IC", process: "IC billing", metric: "Billing raised without a counterparty reference", against: "Against all intercompany invoices due in the period" },
  { domain: "IC", code: "IC", process: "IC billing", metric: "Invoices raised after the billing cut-off", against: "Against all intercompany invoices due in the period" },
  { domain: "IC", code: "IC", process: "IC billing", metric: "Billing value differing from the agreement", against: "Against all intercompany invoices due in the period" },
  { domain: "IC", code: "IC", process: "IC AP booking", metric: "Invoices not booked by the counterparty", against: "Against all intercompany invoices raised" },
  { domain: "IC", code: "IC", process: "IC AP booking", metric: "Bookings with no matching billing document", against: "Against all intercompany invoices raised" },
  { domain: "IC", code: "IC", process: "IC AP booking", metric: "Booking date outside the billing period", against: "Against all intercompany invoices raised" },
  { domain: "IC", code: "IC", process: "IC AP booking", metric: "Intercompany bookings blocked for payment", against: "Against all intercompany invoices raised" },
  { domain: "IC", code: "IC", process: "IC settlement", metric: "Balances unsettled beyond policy", against: "Against all open intercompany balances" },
  { domain: "IC", code: "IC", process: "IC settlement", metric: "Settlements with no netting reference", against: "Against all open intercompany balances" },
  { domain: "IC", code: "IC", process: "IC settlement", metric: "Part-settled intercompany invoices open", against: "Against all open intercompany balances" },
  { domain: "IC", code: "IC", process: "IC settlement", metric: "Settlement value differences", against: "Against all open intercompany balances" },
  { domain: "IC", code: "IC", process: "IC cash application", metric: "Intercompany receipts unapplied", against: "Against all intercompany receipts in the period" },
  { domain: "IC", code: "IC", process: "IC cash application", metric: "Receipts applied against the wrong entity", against: "Against all intercompany receipts in the period" },
  { domain: "IC", code: "IC", process: "IC cash application", metric: "Cash applied with no remittance reference", against: "Against all intercompany receipts in the period" },
  { domain: "IC", code: "IC", process: "IC cash application", metric: "Intercompany receipts held in suspense", against: "Against all intercompany receipts in the period" },
  { domain: "IC", code: "IC", process: "IC balance confirmation", metric: "Confirmations not received", against: "Against all counterparty entities in scope" },
  { domain: "IC", code: "IC", process: "IC balance confirmation", metric: "Confirmations returned with differences", against: "Against all counterparty entities in scope" },
  { domain: "IC", code: "IC", process: "IC balance confirmation", metric: "Confirmations unsigned by the counterparty", against: "Against all counterparty entities in scope" },
  { domain: "IC", code: "IC", process: "IC balance confirmation", metric: "Confirmation differences unexplained", against: "Against all counterparty entities in scope" },
  { domain: "IC", code: "IC", process: "IC elimination readiness", metric: "Intercompany pairs not matched for elimination", against: "Against all intercompany pairs in the period" },
  { domain: "IC", code: "IC", process: "IC elimination readiness", metric: "One-sided intercompany entries", against: "Against all intercompany pairs in the period" },
  { domain: "IC", code: "IC", process: "IC elimination readiness", metric: "Non-intercompany postings in IC accounts", against: "Against all intercompany pairs in the period" },
  { domain: "IC", code: "IC", process: "IC elimination readiness", metric: "Elimination differences above threshold", against: "Against all intercompany pairs in the period" },
  { domain: "IC", code: "IC", process: "IC transfer pricing and recharges", metric: "Transactions with no agreed markup", against: "Against all intercompany transactions in the period" },
  { domain: "IC", code: "IC", process: "IC transfer pricing and recharges", metric: "Markup applied outside the agreed range", against: "Against all intercompany transactions in the period" },
  { domain: "IC", code: "IC", process: "IC transfer pricing and recharges", metric: "Transfer pricing documentation missing for the period", against: "Against all intercompany transactions in the period" },
  { domain: "IC", code: "IC", process: "IC transfer pricing and recharges", metric: "Agreed recharges not raised", against: "Against all intercompany transactions in the period" },
  { domain: "CF", code: "CF", process: "General ledger", metric: "Journals unposted at close", against: "Against all journals in the period" },
  { domain: "CF", code: "CF", process: "General ledger", metric: "Journals pending approval", against: "Against all journals in the period" },
  { domain: "CF", code: "CF", process: "General ledger", metric: "Trial balance debit and credit difference", against: "Against all journals in the period" },
  { domain: "CF", code: "CF", process: "General ledger", metric: "Journals posted into a closed period", against: "Against all journals in the period" },
  { domain: "CF", code: "CF", process: "General ledger", metric: "Suspense account balances open", against: "Against all journals in the period" },
  { domain: "CF", code: "CF", process: "General ledger", metric: "Manual journals above the review threshold", against: "Against all journals in the period" },
  { domain: "CF", code: "CF", process: "Accounts payable", metric: "Invoices blocked for payment", against: "Against all open vendor items" },
  { domain: "CF", code: "CF", process: "Accounts payable", metric: "Invoices with no goods receipt", against: "Against all open vendor items" },
  { domain: "CF", code: "CF", process: "Accounts payable", metric: "Invoices pending approval beyond SLA", against: "Against all open vendor items" },
  { domain: "CF", code: "CF", process: "Accounts payable", metric: "Debit balances sitting in vendor accounts", against: "Against all open vendor items" },
  { domain: "CF", code: "CF", process: "Accounts payable", metric: "GR/IR items open beyond ageing policy", against: "Against all open vendor items" },
  { domain: "CF", code: "CF", process: "Accounts payable", metric: "Vendor advances unadjusted", against: "Against all open vendor items" },
  { domain: "CF", code: "CF", process: "Accounts receivable", metric: "Receivables overdue beyond policy", against: "Against all open customer items" },
  { domain: "CF", code: "CF", process: "Accounts receivable", metric: "Receipts unapplied against invoices", against: "Against all open customer items" },
  { domain: "CF", code: "CF", process: "Accounts receivable", metric: "Credit balances sitting in customer accounts", against: "Against all open customer items" },
  { domain: "CF", code: "CF", process: "Accounts receivable", metric: "Customer credit limits breached", against: "Against all open customer items" },
  { domain: "CF", code: "CF", process: "Accounts receivable", metric: "Disputed invoices open", against: "Against all open customer items" },
  { domain: "CF", code: "CF", process: "Accounts receivable", metric: "Bad debt provision not updated for the period", against: "Against all open customer items" },
  { domain: "CF", code: "CF", process: "Fixed assets", metric: "Assets not capitalised from work in progress", against: "Against all assets in the register" },
  { domain: "CF", code: "CF", process: "Fixed assets", metric: "Depreciation not run for the period", against: "Against all assets in the register" },
  { domain: "CF", code: "CF", process: "Fixed assets", metric: "Assets with no location or custodian", against: "Against all assets in the register" },
  { domain: "CF", code: "CF", process: "Fixed assets", metric: "Disposals not accounted", against: "Against all assets in the register" },
  { domain: "CF", code: "CF", process: "Fixed assets", metric: "Asset register to GL difference", against: "Against all assets in the register" },
  { domain: "CF", code: "CF", process: "Bank and cash", metric: "Reconciling items open beyond ageing policy", against: "Against all bank and cash accounts" },
  { domain: "CF", code: "CF", process: "Bank and cash", metric: "Bank accounts not reconciled for the period", against: "Against all bank and cash accounts" },
  { domain: "CF", code: "CF", process: "Bank and cash", metric: "Cheques issued and unpresented beyond validity", against: "Against all bank and cash accounts" },
  { domain: "CF", code: "CF", process: "Bank and cash", metric: "Cash on hand to book difference", against: "Against all bank and cash accounts" },
  { domain: "CF", code: "CF", process: "Bank and cash", metric: "Bank charges and interest not accounted", against: "Against all bank and cash accounts" },
  { domain: "GA", code: "GA", process: "Master data readiness", metric: "Inactive cost centres carrying balances", against: "Against all active master records" },
  { domain: "GA", code: "GA", process: "Master data readiness", metric: "Blocked GL accounts with open items", against: "Against all active master records" },
  { domain: "GA", code: "GA", process: "Master data readiness", metric: "Master data changes pending approval", against: "Against all active master records" },
  { domain: "GA", code: "GA", process: "Sub-ledger close", metric: "Sub-ledgers not closed for the period", against: "Against all sub-ledgers in scope" },
  { domain: "GA", code: "GA", process: "Sub-ledger close", metric: "Sub-ledger to GL differences", against: "Against all sub-ledgers in scope" },
  { domain: "GA", code: "GA", process: "Sub-ledger close", metric: "Postings made after sub-ledger close", against: "Against all sub-ledgers in scope" },
  { domain: "GA", code: "GA", process: "Accruals", metric: "Accruals not raised for known obligations", against: "Against all known obligations in the period" },
  { domain: "GA", code: "GA", process: "Accruals", metric: "Prior-period accruals not reversed", against: "Against all known obligations in the period" },
  { domain: "GA", code: "GA", process: "Accruals", metric: "Accrual value variance against actual", against: "Against all known obligations in the period" },
  { domain: "GA", code: "GA", process: "Provisions", metric: "Provisions not reviewed for the period", against: "Against all provision accounts" },
  { domain: "GA", code: "GA", process: "Provisions", metric: "Provisions carrying no supporting basis", against: "Against all provision accounts" },
  { domain: "GA", code: "GA", process: "Provisions", metric: "Provision releases without approval", against: "Against all provision accounts" },
  { domain: "GA", code: "GA", process: "Prepaid and deferred", metric: "Prepaid schedules not amortised", against: "Against all prepaid and deferred schedules" },
  { domain: "GA", code: "GA", process: "Prepaid and deferred", metric: "Deferred charges with no schedule", against: "Against all prepaid and deferred schedules" },
  { domain: "GA", code: "GA", process: "Prepaid and deferred", metric: "Fully amortised balances still open", against: "Against all prepaid and deferred schedules" },
  { domain: "GA", code: "GA", process: "Reclassifications", metric: "Reclass entries pending", against: "Against all reclass entries in the period" },
  { domain: "GA", code: "GA", process: "Reclassifications", metric: "Reclass entries with no narration", against: "Against all reclass entries in the period" },
  { domain: "GA", code: "GA", process: "Reclassifications", metric: "Reclasses repeating across periods", against: "Against all reclass entries in the period" },
  { domain: "GA", code: "GA", process: "Foreign exchange", metric: "Revaluation not run for the period", against: "Against all open items in foreign currency" },
  { domain: "GA", code: "GA", process: "Foreign exchange", metric: "Open items with no valid exchange rate", against: "Against all open items in foreign currency" },
  { domain: "GA", code: "GA", process: "Foreign exchange", metric: "Exchange differences above threshold", against: "Against all open items in foreign currency" },
  { domain: "GA", code: "GA", process: "Payroll accounting", metric: "Payroll postings not reconciled to the register", against: "Against all payroll runs in the period" },
  { domain: "GA", code: "GA", process: "Payroll accounting", metric: "Statutory deductions not deposited", against: "Against all payroll runs in the period" },
  { domain: "GA", code: "GA", process: "Payroll accounting", metric: "Payroll suspense balances open", against: "Against all payroll runs in the period" },
  { domain: "GA", code: "GA", process: "Tax accounting", metric: "Tax ledger to return difference", against: "Against all tax GL accounts and returns" },
  { domain: "GA", code: "GA", process: "Tax accounting", metric: "Tax provisions not updated for the period", against: "Against all tax GL accounts and returns" },
  { domain: "GA", code: "GA", process: "Tax accounting", metric: "Withholding not deposited for the period", against: "Against all tax GL accounts and returns" },
  { domain: "GA", code: "GA", process: "Inventory accounting", metric: "Stock ledger to GL difference", against: "Against all stock and GRIR balances" },
  { domain: "GA", code: "GA", process: "Inventory accounting", metric: "GRIR balances open beyond policy", against: "Against all stock and GRIR balances" },
  { domain: "GA", code: "GA", process: "Inventory accounting", metric: "Inventory provisions not posted", against: "Against all stock and GRIR balances" },
  { domain: "GA", code: "GA", process: "Cost of sales", metric: "Cost of sales not matched to revenue recognised", against: "Against all revenue lines in the period" },
  { domain: "GA", code: "GA", process: "Cost of sales", metric: "Standard cost variances unabsorbed", against: "Against all revenue lines in the period" },
  { domain: "GA", code: "GA", process: "Cost of sales", metric: "Cost postings with no cost object", against: "Against all revenue lines in the period" },
  { domain: "GA", code: "GA", process: "Close task management", metric: "Close tasks not started", against: "Against all tasks on the close calendar" },
  { domain: "GA", code: "GA", process: "Close task management", metric: "Close tasks breaching their SLA", against: "Against all tasks on the close calendar" },
  { domain: "GA", code: "GA", process: "Close task management", metric: "Close tasks completed with no evidence attached", against: "Against all tasks on the close calendar" },
  { domain: "GA", code: "GA", process: "P&L review", metric: "Lines with variance above threshold", against: "Against all P&L lines under review" },
  { domain: "GA", code: "GA", process: "P&L review", metric: "Variance explanations not provided", against: "Against all P&L lines under review" },
  { domain: "GA", code: "GA", process: "P&L review", metric: "Review sign-off pending", against: "Against all P&L lines under review" },
  { domain: "TF", code: "TF", process: "Procure to pay", metric: "Three-way match exceptions open", against: "Against all purchase transactions in the period" },
  { domain: "TF", code: "TF", process: "Procure to pay", metric: "GR/IR items unmatched", against: "Against all purchase transactions in the period" },
  { domain: "TF", code: "TF", process: "Procure to pay", metric: "Purchase orders open beyond the delivery date", against: "Against all purchase transactions in the period" },
  { domain: "TF", code: "TF", process: "Procure to pay", metric: "Invoices with no valid purchase order", against: "Against all purchase transactions in the period" },
  { domain: "TF", code: "TF", process: "Procure to pay", metric: "Duplicate invoice candidates open", against: "Against all purchase transactions in the period" },
  { domain: "TF", code: "TF", process: "Order to cash", metric: "Unbilled revenue open", against: "Against all sales transactions in the period" },
  { domain: "TF", code: "TF", process: "Order to cash", metric: "Billing blocks on delivered orders", against: "Against all sales transactions in the period" },
  { domain: "TF", code: "TF", process: "Order to cash", metric: "Deliveries with no invoice raised", against: "Against all sales transactions in the period" },
  { domain: "TF", code: "TF", process: "Order to cash", metric: "Credit notes pending approval", against: "Against all sales transactions in the period" },
  { domain: "TF", code: "TF", process: "Order to cash", metric: "Sales orders open beyond the cycle", against: "Against all sales transactions in the period" },
  { domain: "TF", code: "TF", process: "Inventory movement", metric: "Movements with no valid material to GL mapping", against: "Against all stock movements in the period" },
  { domain: "TF", code: "TF", process: "Inventory movement", metric: "Backdated stock postings", against: "Against all stock movements in the period" },
  { domain: "TF", code: "TF", process: "Inventory movement", metric: "Stock in transit beyond ageing policy", against: "Against all stock movements in the period" },
  { domain: "TF", code: "TF", process: "Inventory movement", metric: "Quarantine and blocked stock unresolved", against: "Against all stock movements in the period" },
  { domain: "TF", code: "TF", process: "Inventory movement", metric: "Physical count differences unposted", against: "Against all stock movements in the period" },
  { domain: "TF", code: "TF", process: "Payroll processing", metric: "Payroll runs not posted to finance", against: "Against all payroll transactions in the period" },
  { domain: "TF", code: "TF", process: "Payroll processing", metric: "Payments to employees with no active record", against: "Against all payroll transactions in the period" },
  { domain: "TF", code: "TF", process: "Payroll processing", metric: "Off-cycle payments without approval", against: "Against all payroll transactions in the period" },
  { domain: "TF", code: "TF", process: "Payroll processing", metric: "Reimbursements pending beyond SLA", against: "Against all payroll transactions in the period" },
  { domain: "TF", code: "TF", process: "Payroll processing", metric: "Payroll accrual not raised", against: "Against all payroll transactions in the period" },
  { domain: "RC", code: "RC", process: "Financial statement preparation", metric: "Statements not prepared for the period", against: "Against all statements and schedules due" },
  { domain: "RC", code: "RC", process: "Financial statement preparation", metric: "Supporting schedules pending", against: "Against all statements and schedules due" },
  { domain: "RC", code: "RC", process: "Financial statement preparation", metric: "Notes to accounts incomplete", against: "Against all statements and schedules due" },
  { domain: "RC", code: "RC", process: "Financial statement preparation", metric: "Prior period comparatives not restated", against: "Against all statements and schedules due" },
  { domain: "RC", code: "RC", process: "Consolidation", metric: "Entities not submitted for consolidation", against: "Against all entities in the consolidation scope" },
  { domain: "RC", code: "RC", process: "Consolidation", metric: "Elimination entries pending", against: "Against all entities in the consolidation scope" },
  { domain: "RC", code: "RC", process: "Consolidation", metric: "Consolidation adjustments unapproved", against: "Against all entities in the consolidation scope" },
  { domain: "RC", code: "RC", process: "Consolidation", metric: "Minority interest not computed", against: "Against all entities in the consolidation scope" },
  { domain: "RC", code: "RC", process: "GAAP and standards adjustments", metric: "Local to group GAAP entries pending", against: "Against all reporting adjustments due" },
  { domain: "RC", code: "RC", process: "GAAP and standards adjustments", metric: "New standard adjustments not applied", against: "Against all reporting adjustments due" },
  { domain: "RC", code: "RC", process: "GAAP and standards adjustments", metric: "Lease schedules not updated", against: "Against all reporting adjustments due" },
  { domain: "RC", code: "RC", process: "GAAP and standards adjustments", metric: "Revenue recognition adjustments pending", against: "Against all reporting adjustments due" },
  { domain: "RC", code: "RC", process: "Statutory reporting", metric: "Filings pending for the period", against: "Against all filings due in the period" },
  { domain: "RC", code: "RC", process: "Statutory reporting", metric: "Filings submitted after the due date", against: "Against all filings due in the period" },
  { domain: "RC", code: "RC", process: "Statutory reporting", metric: "Supporting schedules not attached", against: "Against all filings due in the period" },
  { domain: "RC", code: "RC", process: "Statutory reporting", metric: "Regulator queries open", against: "Against all filings due in the period" },
  { domain: "RC", code: "RC", process: "Internal controls", metric: "Control tests not performed", against: "Against all controls in the period test plan" },
  { domain: "RC", code: "RC", process: "Internal controls", metric: "Controls failed and unremediated", against: "Against all controls in the period test plan" },
  { domain: "RC", code: "RC", process: "Internal controls", metric: "Segregation of duties conflicts open", against: "Against all controls in the period test plan" },
  { domain: "RC", code: "RC", process: "Internal controls", metric: "Control evidence not attached", against: "Against all controls in the period test plan" },
  { domain: "RC", code: "RC", process: "Audit support", metric: "Audit requests open beyond SLA", against: "Against all audit requests and observations" },
  { domain: "RC", code: "RC", process: "Audit support", metric: "Audit observations unremediated", against: "Against all audit requests and observations" },
  { domain: "RC", code: "RC", process: "Audit support", metric: "Evidence packs incomplete", against: "Against all audit requests and observations" },
  { domain: "RC", code: "RC", process: "Audit support", metric: "Prior year points carried forward", against: "Against all audit requests and observations" },
  { domain: "RC", code: "RC", process: "Disclosure and notes", metric: "Related party disclosures incomplete", against: "Against all disclosures required for the period" },
  { domain: "RC", code: "RC", process: "Disclosure and notes", metric: "Contingent liabilities not updated", against: "Against all disclosures required for the period" },
  { domain: "RC", code: "RC", process: "Disclosure and notes", metric: "Commitments schedule pending", against: "Against all disclosures required for the period" },
  { domain: "RC", code: "RC", process: "Disclosure and notes", metric: "Subsequent events not reviewed", against: "Against all disclosures required for the period" },
  { domain: "RC", code: "RC", process: "Sign-off and certification", metric: "Entity sign-offs pending", against: "Against all entities and owners required to sign off" },
  { domain: "RC", code: "RC", process: "Sign-off and certification", metric: "Sign-offs recorded with no supporting evidence", against: "Against all entities and owners required to sign off" },
  { domain: "RC", code: "RC", process: "Sign-off and certification", metric: "Certifications submitted late", against: "Against all entities and owners required to sign off" },
  { domain: "RC", code: "RC", process: "Sign-off and certification", metric: "Sign-off exceptions unresolved", against: "Against all entities and owners required to sign off" },
  { domain: "RC", code: "RC", process: "Sign-off and certification", metric: "Close period not locked", against: "Against all entities and owners required to sign off" },
  { domain: "FP", code: "FP", process: "Budget preparation", metric: "Budget inputs not submitted", against: "Against all budget lines in scope" },
  { domain: "FP", code: "FP", process: "Budget preparation", metric: "Budget lines with no owner", against: "Against all budget lines in scope" },
  { domain: "FP", code: "FP", process: "Budget preparation", metric: "Submissions after the cut-off", against: "Against all budget lines in scope" },
  { domain: "FP", code: "FP", process: "Budget approval", metric: "Budgets pending approval", against: "Against all budgets awaiting approval" },
  { domain: "FP", code: "FP", process: "Budget approval", metric: "Approvals outside the delegation matrix", against: "Against all budgets awaiting approval" },
  { domain: "FP", code: "FP", process: "Budget approval", metric: "Approved budgets not uploaded", against: "Against all budgets awaiting approval" },
  { domain: "FP", code: "FP", process: "Forecasting", metric: "Forecast not submitted for the period", against: "Against all forecast lines in the cycle" },
  { domain: "FP", code: "FP", process: "Forecasting", metric: "Forecast lines unchanged from the prior cycle", against: "Against all forecast lines in the cycle" },
  { domain: "FP", code: "FP", process: "Forecasting", metric: "Forecast horizon incomplete", against: "Against all forecast lines in the cycle" },
  { domain: "FP", code: "FP", process: "Forecast accuracy", metric: "Forecast variance above threshold", against: "Against all forecast lines with an actual" },
  { domain: "FP", code: "FP", process: "Forecast accuracy", metric: "Variance repeating across cycles", against: "Against all forecast lines with an actual" },
  { domain: "FP", code: "FP", process: "Forecast accuracy", metric: "Accuracy commentary not provided", against: "Against all forecast lines with an actual" },
  { domain: "FP", code: "FP", process: "Budget against actual", metric: "Cost centres overspent against budget", against: "Against all cost centres with a budget" },
  { domain: "FP", code: "FP", process: "Budget against actual", metric: "Variances with no explanation", against: "Against all cost centres with a budget" },
  { domain: "FP", code: "FP", process: "Budget against actual", metric: "Variance approvals pending", against: "Against all cost centres with a budget" },
  { domain: "FP", code: "FP", process: "Margin analysis", metric: "Lines below target margin", against: "Against all products and services with a target margin" },
  { domain: "FP", code: "FP", process: "Margin analysis", metric: "Margin declining against the prior period", against: "Against all products and services with a target margin" },
  { domain: "FP", code: "FP", process: "Margin analysis", metric: "Margin drivers not explained", against: "Against all products and services with a target margin" },
  { domain: "FP", code: "FP", process: "Capital expenditure planning", metric: "Capex approved and unspent", against: "Against all approved capex items" },
  { domain: "FP", code: "FP", process: "Capital expenditure planning", metric: "Capex spent without approval", against: "Against all approved capex items" },
  { domain: "FP", code: "FP", process: "Capital expenditure planning", metric: "Capex milestones missed", against: "Against all approved capex items" },
  { domain: "FP", code: "FP", process: "Cash flow planning", metric: "Cash forecast variance above threshold", against: "Against all cash forecast lines" },
  { domain: "FP", code: "FP", process: "Cash flow planning", metric: "Funding gaps flagged and open", against: "Against all cash forecast lines" },
  { domain: "FP", code: "FP", process: "Cash flow planning", metric: "Working capital days above target", against: "Against all cash forecast lines" },
  { domain: "PC", code: "PC", process: "Cost allocation", metric: "Costs unallocated at period end", against: "Against all costs subject to allocation" },
  { domain: "PC", code: "PC", process: "Cost allocation", metric: "Allocation cycles not run", against: "Against all costs subject to allocation" },
  { domain: "PC", code: "PC", process: "Cost allocation", metric: "Allocation rules with no owner", against: "Against all costs subject to allocation" },
  { domain: "PC", code: "PC", process: "Cost allocation", metric: "Costs allocated to inactive objects", against: "Against all costs subject to allocation" },
  { domain: "PC", code: "PC", process: "Cost allocation", metric: "Allocation results not reviewed", against: "Against all costs subject to allocation" },
  { domain: "PC", code: "PC", process: "Profit centre control", metric: "Profit centres in loss against plan", against: "Against all active profit centres" },
  { domain: "PC", code: "PC", process: "Profit centre control", metric: "Profit centres with no responsible owner", against: "Against all active profit centres" },
  { domain: "PC", code: "PC", process: "Profit centre control", metric: "Inter-profit-centre postings unmatched", against: "Against all active profit centres" },
  { domain: "PC", code: "PC", process: "Profit centre control", metric: "Profit centre mapping errors", against: "Against all active profit centres" },
  { domain: "PC", code: "PC", process: "Profit centre control", metric: "Segment results not reconciled to the P&L", against: "Against all active profit centres" },
  { domain: "PC", code: "PC", process: "Management reporting", metric: "MIS packs not published", against: "Against all reports and actions in the review pack" },
  { domain: "PC", code: "PC", process: "Management reporting", metric: "Actions from the prior review still open", against: "Against all reports and actions in the review pack" },
  { domain: "PC", code: "PC", process: "Management reporting", metric: "Reports published with no reconciliation to the GL", against: "Against all reports and actions in the review pack" },
  { domain: "PC", code: "PC", process: "Management reporting", metric: "KPI definitions changed without approval", against: "Against all reports and actions in the review pack" },
  { domain: "PC", code: "PC", process: "Management reporting", metric: "Management review sign-off pending", against: "Against all reports and actions in the review pack" },
  { domain: "IR", code: "IR", process: "Anomaly detection", metric: "Critical anomalies detected", against: "Against all transactions scored in the period" },
  { domain: "IR", code: "IR", process: "Anomaly detection", metric: "Anomalies open beyond SLA", against: "Against all transactions scored in the period" },
  { domain: "IR", code: "IR", process: "Duplicate and leakage detection", metric: "Duplicate payment candidates open", against: "Against all payments and claims in the period" },
  { domain: "IR", code: "IR", process: "Duplicate and leakage detection", metric: "Recovery opportunities identified and not actioned", against: "Against all payments and claims in the period" },
  { domain: "IR", code: "IR", process: "Recovery tracking", metric: "Recovery actions pending", against: "Against all recoveries raised" },
  { domain: "IR", code: "IR", process: "Recovery tracking", metric: "Recoveries raised and not collected", against: "Against all recoveries raised" },
  { domain: "IR", code: "IR", process: "Manual intervention", metric: "Manual journals to control accounts", against: "Against all postings in the period" },
  { domain: "IR", code: "IR", process: "Manual intervention", metric: "Manual overrides of system-proposed values", against: "Against all postings in the period" },
  { domain: "IR", code: "IR", process: "Access and authorisation", metric: "Postings by users outside their role", against: "Against all users and master data changes" },
  { domain: "IR", code: "IR", process: "Access and authorisation", metric: "Unauthorised master data changes", against: "Against all users and master data changes" },
  { domain: "IR", code: "IR", process: "Audit trail integrity", metric: "Transactions with an incomplete audit trail", against: "Against all transactions in the period" },
  { domain: "IR", code: "IR", process: "Audit trail integrity", metric: "Backdated changes after sign-off", against: "Against all transactions in the period" },
  { domain: "IR", code: "IR", process: "Fraud indicators", metric: "Vendor bank detail changed before payment", against: "Against all payments and vendor changes" },
  { domain: "IR", code: "IR", process: "Fraud indicators", metric: "Payments just below an approval threshold", against: "Against all payments and vendor changes" },
  { domain: "IR", code: "IR", process: "Predictive close risk", metric: "Close tasks predicted to breach", against: "Against all domains and close tasks" },
  { domain: "IR", code: "IR", process: "Predictive close risk", metric: "Domains trending red against the prior close", against: "Against all domains and close tasks" },
  { domain: "IR", code: "IR", process: "Predictive close risk", metric: "Exceptions repeating across three closes", against: "Against all domains and close tasks" },
];
